apiVersion: v1
kind: Pod
metadata:
  name: busybox-echo
  namespace: farrukh-final
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo The BEST DevOps COURSE!!! && sleep 3600']
