apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-admin-to-flask
  namespace: farrukh-final
spec:
  podSelector:
    matchLabels:
      app: flask-application
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: admin
  policyTypes:
    - Ingress
