apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-exam-host
  namespace: farrukh-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-host
  template:
    metadata:
      labels:
        app: exam-host
    spec:
      containers:
        - name: app
          image: nvrbckdown/flask-app:final-exam
          volumeMounts:
            - name: host-volume
              mountPath: /mnt
      volumes:
        - name: host-volume
          hostPath:
            path: /mnt
            type: Directory
