apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap
  namespace: farrukh-final
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["sh", "-c"]
      args:
        - echo "My name is $AUTHOR and this is my $EXAM_TYPE" && sleep 3600
      envFrom:
        - configMapRef:
            name: configmap-farrukh
